spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge03_ms_products
    username: root
    password: Linha123@
  application:
    name: PRODUCT-SERVICE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8000


eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/


app:
  jwt-secret: 7418df96f38366fa21b8b75a23f8ae666ac936824dfe4d172f9b03f8fbce5a1c
