spring:
  datasource:
    url: jdbc:mysql://localhost:3306/challenge03_ms_users
    username: root
    password: Linha123@
  application:
    name: USER-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8100


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

app:
  jwt-secret: 7418df96f38366fa21b8b75a23f8ae666ac936824dfe4d172f9b03f8fbce5a1c
  jwt-expiration-milliseconds: 604800000